### ISSUE TITLE
Odd discrepancy in "bonus" parameter of Attack(bonus, damage dice) constructor.

### ISSUE THREAD

**Issue by colinhowell** [danielrcollins1/Arena#2]
https://github.com/danielrcollins1/Arena/blob/89323f4240f0c998164d3aa6e0c8df1e77a4c823/Attack.java#L47-L52

Is the parameter "bonus" here really supposed to be a bonus value, or is it rather a rate value that was misnamed in copy-pasting the preceding (rate, bonus, damage dice) constructor? Because as written, the constructor actually uses the "bonus" value to set the Attack object's "rate" field, rather than its "bonus" field (which it sets to 1).

Admittedly this is only a nitpick, since from what I can see (assuming GitHub's cross-referencing is complete), this constructor isn't used in any actual application code, only in the main() static test methods for the Attack, Monster, and Party classes. The latter two use it in such a way that its effect is obscured. But in the Attack class's test method, the output for the "Attack(2, 1)" case shows that the rate field is set to 2 and the bonus field to 1.

**Comment by danielrcollins1** [comment]
Hey, thanks for this. The intent was to have that really be an attack bonus, but I flipped-flopped the rate/bonus arguments to the base constructor. Clearly the default value of "1" was meant to be a basic 1 attack per round rate value. Thanks for looking at this so closely!
